### ISSUE TITLE
The program I compiled does not run properly，please help me to check where is my fault.

### ISSUE THREAD

**Issue by xinfenglee** [Bwar/Nebio#1]
![image](https://user-images.githubusercontent.com/42239534/99329546-701de400-28b9-11eb-9610-310f92053199.png)

**Comment by Bwar** [comment]
There is a little change in Nebula 1.x which is not compatible with Nebio and I will fix it this week. Or you are able to fix it by add "#include <channel/SocketChannel.hpp>"... to the source file yourself,  cd the Nebio source path then make  and find the missing header includes.

**Comment by xinfenglee** [comment]
编译的问题已经解决的了 现在是我没法验证功能是否正常 这个id打印出来也不对 查看beacon一直都是不在线的
![image](https://user-images.githubusercontent.com/42239534/99369685-b134e900-28f7-11eb-834a-3bbe9dc40a15.png)

![image](https://user-images.githubusercontent.com/42239534/99369560-8ba7df80-28f7-11eb-8d01-61903d930d63.png)

**Comment by Bwar** [comment]
beacon节点的主从信息不会影响集群其他节点之间的通信。
show beacon之所以显示异常应该是因为Beacon的配置文件["custom"]["local_config"]["beacon"]数组没有配置导致的。 custom外面那个beacon配置是用于其他节点向beacon注册的，而Beacon配置文件里的["custom"]["local_config"]["beacon"]才是beacon多节点之间通信使用。  beacon的主从选举、切换都是属于插件功能，不属于Nebula框架，所以其配置也是Beacon节点的自定义配置。

**Comment by xinfenglee** [comment]
![image](https://user-images.githubusercontent.com/42239534/99468817-7628c900-297c-11eb-9b44-d7e2c9ce2db7.png)
我配置了该节点 但是显示还是没有leader跟on_line的 是不是我哪里配置错误了 还是没有这个主从选举的插件?


![image](https://user-images.githubusercontent.com/42239534/99468778-58f3fa80-297c-11eb-94c4-939e84290da7.png)

**Comment by Bwar** [comment]
beacon配置格式有误，正确的格式是   "beacon":["192.168.1.11:16000", "192.168.1.12:16000"]
选举插件的加载可以参考 [https://github.com/Bwar/NebulaBeacon/blob/master/conf/NebulaBeacon.json](https://github.com/Bwar/NebulaBeacon/blob/master/conf/NebulaBeacon.json) 里的配置。

**Comment by xinfenglee** [comment]
非常感谢 我试试
